---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "pingpong"
  namespace: pp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: "pingpong"
      namespace: pp
    spec:
      containers:
      - name: "pingpong"
        image: "iamsteveholmes/pingpong:0.1"
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ping-service
  namespace: pp
spec:
  selector:
    app: pingpong
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: crd-operator
  namespace: pp
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: crd-operator
    app.kubernetes.io/version: "0.1"
  type: ClusterIP
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pingserverresources.chorgi.io
spec:
  group: chorgi.io
  names:
    kind: PingServerResource
    plural: pingserverresources
    singular: pingserverresource
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                replicas:
                  type: integer
              type: object
            status:
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crd-operator
  namespace: pp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: crd-operator
      app.kubernetes.io/version: "0.1"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: crd-operator
        app.kubernetes.io/version: "0.1"
      namespace: pp
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: registry.hub.docker.com/iamsteveholmes/crd-operator:0.1
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: crd-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: crd-operator
